/**
 * Helpers de acentuacao para textos exibidos em PDFs.
 *
 * Convenção do projeto: codigo e dados ficam sem acento em portugues; mas
 * conteudo gerado em PDFs (apresentado a clientes) deve trazer a grafia
 * correta. Este modulo concentra os mapeamentos necessarios.
 */
import type { Grau, Risco, TipoProcesso, TipoProcessoTce } from "@prisma/client";

// =================== Mapeamento palavra-a-palavra ===================
// As regras sao aplicadas com word-boundary (\b) e case-insensitive,
// preservando capitalizacao da palavra original.

const MAPEAMENTO: ReadonlyArray<readonly [string, string]> = [
  // Termos juridicos comuns
  ["acao", "ação"],
  ["acoes", "ações"],
  ["acordao", "acórdão"],
  ["acordaos", "acórdãos"],
  ["acordo", "acordo"],
  ["agravo", "agravo"],
  ["alegacao", "alegação"],
  ["alegacoes", "alegações"],
  ["anulatoria", "anulatória"],
  ["apelacao", "apelação"],
  ["apelacoes", "apelações"],
  ["aprovacao", "aprovação"],
  ["arquivamento", "arquivamento"],
  ["audiencia", "audiência"],
  ["audiencias", "audiências"],
  ["autuacao", "autuação"],
  ["autuacoes", "autuações"],
  ["camara", "câmara"],
  ["camaras", "câmaras"],
  ["cautelar", "cautelar"],
  ["cautelares", "cautelares"],
  ["competencia", "competência"],
  ["competencias", "competências"],
  ["conciliacao", "conciliação"],
  ["conclusao", "conclusão"],
  ["conclusoes", "conclusões"],
  ["condenacao", "condenação"],
  ["condenacoes", "condenações"],
  ["confidencial", "Confidencial"],
  ["conselheiro", "conselheiro"],
  ["conselheiros", "conselheiros"],
  ["consulta", "consulta"],
  ["contestacao", "contestação"],
  ["contestacoes", "contestações"],
  ["contrarrazoes", "contrarrazões"],
  ["criminal", "criminal"],
  ["debito", "débito"],
  ["decisao", "decisão"],
  ["decisoes", "decisões"],
  ["declaracao", "declaração"],
  ["declaracoes", "declarações"],
  ["declaratoria", "declaratória"],
  ["denuncia", "denúncia"],
  ["denuncias", "denúncias"],
  ["desfavoravel", "desfavorável"],
  ["desfavoraveis", "desfavoráveis"],
  ["desfavoravelis", "desfavoráveis"],
  ["devolucao", "devolução"],
  ["devolucoes", "devoluções"],
  ["distribuicao", "distribuição"],
  ["divida", "dívida"],
  ["dominio", "domínio"],
  ["embargos", "embargos"],
  ["embargo", "embargo"],
  ["erario", "erário"],
  ["estrategia", "estratégia"],
  ["estrategica", "estratégica"],
  ["estrategicas", "estratégicas"],
  ["estrategico", "estratégico"],
  ["estrategicos", "estratégicos"],
  ["execucao", "execução"],
  ["execucoes", "execuções"],
  ["exercicio", "exercício"],
  ["exercicios", "exercícios"],
  ["extincao", "extinção"],
  ["extincoes", "extinções"],
  ["extrajudicial", "extrajudicial"],
  ["fase", "fase"],
  ["favoravel", "favorável"],
  ["favoraveis", "favoráveis"],
  ["favoravelis", "favoráveis"],
  ["fiscal", "fiscal"],
  ["fundamentacao", "fundamentação"],
  ["gestao", "gestão"],
  ["gestoes", "gestões"],
  ["gestor", "gestor"],
  ["gestores", "gestores"],
  ["historico", "histórico"],
  ["historicos", "históricos"],
  ["iliquidavel", "iliquidável"],
  ["iliquidaveis", "iliquidáveis"],
  ["impetrante", "impetrante"],
  ["improbidade", "improbidade"],
  ["inadimplencia", "inadimplência"],
  ["inelegivel", "inelegível"],
  ["inelegibilidade", "inelegibilidade"],
  ["interno", "interno"],
  ["intimacao", "intimação"],
  ["intimacoes", "intimações"],
  ["irregular", "irregular"],
  ["irregularidade", "irregularidade"],
  ["irregularidades", "irregularidades"],
  ["judicial", "judicial"],
  ["judiciais", "judiciais"],
  ["juiz", "juiz"],
  ["juizes", "juízes"],
  ["juizo", "juízo"],
  ["juizos", "juízos"],
  ["julgamento", "julgamento"],
  ["julgamentos", "julgamentos"],
  ["juridica", "jurídica"],
  ["juridicas", "jurídicas"],
  ["juridico", "jurídico"],
  ["juridicos", "jurídicos"],
  ["legitimo", "legítimo"],
  ["liquidez", "liquidez"],
  ["mandado", "mandado"],
  ["medio", "médio"],
  ["media", "média"],
  ["medias", "médias"],
  ["medios", "médios"],
  ["memorial", "memorial"],
  ["memoriais", "memoriais"],
  ["merito", "mérito"],
  ["meritos", "méritos"],
  ["ministerio", "ministério"],
  ["municipio", "município"],
  ["municipios", "municípios"],
  ["multa", "multa"],
  ["multas", "multas"],
  ["nulidade", "nulidade"],
  ["numero", "número"],
  ["numeros", "números"],
  ["objeto", "objeto"],
  ["observacao", "observação"],
  ["observacoes", "observações"],
  ["ordinaria", "ordinária"],
  ["ordinarias", "ordinárias"],
  ["ordinario", "ordinário"],
  ["ordinarios", "ordinários"],
  ["orgao", "órgão"],
  ["orgaos", "órgãos"],
  ["pagina", "página"],
  ["paginas", "páginas"],
  ["parecer", "parecer"],
  ["pareceres", "pareceres"],
  ["pauta", "pauta"],
  ["pautas", "pautas"],
  ["penalidade", "penalidade"],
  ["penalidades", "penalidades"],
  ["pendencia", "pendência"],
  ["pendencias", "pendências"],
  ["pendentes", "pendentes"],
  ["periodo", "período"],
  ["periodos", "períodos"],
  ["plenario", "plenário"],
  ["plenaria", "plenária"],
  ["pleno", "Pleno"],
  ["pratica", "prática"],
  ["preliminar", "preliminar"],
  ["preliminares", "preliminares"],
  ["prescricao", "prescrição"],
  ["prestacao", "prestação"],
  ["prestacoes", "prestações"],
  ["previa", "prévia"],
  ["previas", "prévias"],
  ["previo", "prévio"],
  ["previos", "prévios"],
  ["procedente", "procedente"],
  ["improcedente", "improcedente"],
  ["procedimento", "procedimento"],
  ["processo", "processo"],
  ["processos", "processos"],
  ["procuradoria", "procuradoria"],
  ["prognostico", "prognóstico"],
  ["prognosticos", "prognósticos"],
  ["proxima", "próxima"],
  ["proximas", "próximas"],
  ["proximo", "próximo"],
  ["proximos", "próximos"],
  ["publica", "pública"],
  ["publicas", "públicas"],
  ["publicacao", "publicação"],
  ["publicacoes", "publicações"],
  ["publico", "público"],
  ["publicos", "públicos"],
  ["recurso", "recurso"],
  ["recursos", "recursos"],
  ["regiao", "região"],
  ["regioes", "regiões"],
  ["regimental", "regimental"],
  ["regional", "regional"],
  ["regulares", "regulares"],
  ["regular", "regular"],
  ["rejeicao", "rejeição"],
  ["relator", "relator"],
  ["relatores", "relatores"],
  ["relatoria", "relatoria"],
  ["relatorio", "relatório"],
  ["relatorios", "relatórios"],
  ["replica", "réplica"],
  ["replicas", "réplicas"],
  ["rescisao", "rescisão"],
  ["rescisoes", "rescisões"],
  ["rescisoria", "rescisória"],
  ["resolucao", "resolução"],
  ["resolucoes", "resoluções"],
  ["responsavel", "responsável"],
  ["responsaveis", "responsáveis"],
  ["ressarcimento", "ressarcimento"],
  ["resumo", "resumo"],
  ["retencao", "retenção"],
  ["retorno", "retorno"],
  ["risco", "risco"],
  ["riscos", "riscos"],
  ["secao", "seção"],
  ["secoes", "seções"],
  ["seguranca", "segurança"],
  ["segurancas", "seguranças"],
  ["sentenca", "sentença"],
  ["sentencas", "sentenças"],
  ["sessao", "sessão"],
  ["sessoes", "sessões"],
  ["situacao", "situação"],
  ["situacoes", "situações"],
  ["solucao", "solução"],
  ["solucoes", "soluções"],
  ["substituto", "substituto"],
  ["substitutos", "substitutos"],
  ["sumario", "sumário"],
  ["superior", "superior"],
  ["superiores", "superiores"],
  ["sustentacao", "sustentação"],
  ["tecnica", "técnica"],
  ["tecnicas", "técnicas"],
  ["tecnico", "técnico"],
  ["tecnicos", "técnicos"],
  ["tese", "tese"],
  ["teses", "teses"],
  ["titulo", "título"],
  ["titulos", "títulos"],
  ["transitado", "transitado"],
  ["transito", "trânsito"],
  ["tribunal", "tribunal"],
  ["tributario", "tributário"],
  ["tributaria", "tributária"],
  ["turma", "turma"],
  ["turmas", "turmas"],
  ["tutela", "tutela"],
  ["ultima", "última"],
  ["ultimas", "últimas"],
  ["ultimo", "último"],
  ["ultimos", "últimos"],
  ["unica", "única"],
  ["unicas", "únicas"],
  ["unico", "único"],
  ["unicos", "únicos"],
  ["valido", "válido"],
  ["valida", "válida"],
  ["validas", "válidas"],
  ["validos", "válidos"],
  ["vencimento", "vencimento"],
  ["vencimentos", "vencimentos"],
  ["vinculo", "vínculo"],
  ["vinculos", "vínculos"],
  ["vinculado", "vinculado"],
  ["voto", "voto"],
  ["votos", "votos"],
  // Conectivos / advérbios comuns
  ["nao", "não"],
  ["ja", "já"],
  ["por meio", "por meio"],
  // Nomes proprios comuns (cidades / pessoas)
  ["sao", "São"],
  ["joao", "João"],
  ["antonio", "Antônio"],
  ["fabio", "Fábio"],
  ["julio", "Júlio"],
  ["mario", "Mário"],
  ["gabriel", "Gabriel"],
  ["andre", "André"],
  ["jose", "José"],
  ["agua", "Água"],
  ["aguas", "Águas"],
  ["sertao", "sertão"],
  ["itamaraca", "Itamaracá"],
  ["oroco", "Orocó"],
  ["quipapa", "Quipapá"],
  ["caete", "Caeté"],
  ["caetes", "Caetés"],
  ["paranatama", "Paranatama"],
  ["caruaru", "Caruaru"],
  ["catende", "Catende"],
  ["arcoverde", "Arcoverde"],
  ["dormentes", "Dormentes"],
  ["ipojuca", "Ipojuca"],
  ["inaja", "Inajá"],
  ["ingazeira", "Ingazeira"],
  ["lajedo", "Lajedo"],
  ["manari", "Manari"],
  ["olinda", "Olinda"],
  ["pedra", "Pedra"],
  ["petrolina", "Petrolina"],
  ["salgueiro", "Salgueiro"],
  ["tamandare", "Tamandaré"],
  ["venturosa", "Venturosa"],
  ["garanhuns", "Garanhuns"],
  ["agrestina", "Agrestina"],
  ["maraial", "Maraial"],
  ["betania", "Betânia"],
  ["altinho", "Altinho"],
  ["cabrobo", "Cabrobó"],
  ["canhotinho", "Canhotinho"],
  ["cachoeirinha", "Cachoeirinha"],
];

// Compila os regex em ordem de comprimento descendente para que frases
// mais longas sejam casadas antes que palavras isoladas.
const COMPILED: Array<readonly [RegExp, string]> = [...MAPEAMENTO]
  .sort((a, b) => b[0].length - a[0].length)
  .map(([from, to]) => [
    new RegExp(`\\b${escapeRegex(from)}\\b`, "gi"),
    to,
  ] as const);

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function preserveCase(matched: string, base: string): string {
  if (!matched) return base;
  // ALL CAPS
  if (matched === matched.toUpperCase() && matched.length > 1) {
    return base.toUpperCase();
  }
  // Capitalized first
  if (matched[0] === matched[0].toUpperCase()) {
    return base[0].toUpperCase() + base.slice(1);
  }
  return base.toLowerCase();
}

/**
 * Aplica acentuacao em palavras conhecidas dentro de um texto.
 * Mantem capitalizacao da palavra original.
 */
export function acentuar(texto: string | null | undefined): string {
  if (!texto) return texto ?? "";
  let out = texto;
  for (const [re, base] of COMPILED) {
    out = out.replace(re, (m) => preserveCase(m, base));
  }
  return out;
}

// =================== Maps de labels acentuadas ===================

export const TCE_TIPO_LABELS_PT: Record<TipoProcessoTce, string> = {
  PRESTACAO_CONTAS_GOVERNO: "Prestação de Contas de Governo",
  PRESTACAO_CONTAS_GESTAO: "Prestação de Contas de Gestão",
  AUDITORIA_ESPECIAL: "Auditoria Especial",
  RGF: "Relatório de Gestão Fiscal (RGF)",
  AUTO_INFRACAO: "Auto de Infração",
  MEDIDA_CAUTELAR: "Medida Cautelar",
  TOMADA_CONTAS_ESPECIAL: "Tomada de Contas Especial",
  DESTAQUE: "Destaque",
  DENUNCIA: "Denúncia",
  TERMO_AJUSTE_GESTAO: "Termo de Ajuste de Gestão",
  PEDIDO_RESCISAO: "Pedido de Rescisão",
  CONSULTA: "Consulta",
};

export const TIPO_PROCESSO_LABELS_PT: Record<TipoProcesso, string> = {
  IMPROBIDADE: "Improbidade",
  ACP: "ACP",
  CRIMINAL: "Criminal",
  ACAO_POPULAR: "Ação Popular",
  MANDADO_SEGURANCA: "Mandado de Segurança",
  MANDADO_SEGURANCA_COLETIVO: "Mandado de Segurança Coletivo",
  HABEAS_CORPUS: "Habeas Corpus",
  HABEAS_DATA: "Habeas Data",
  ACAO_RESCISORIA: "Ação Rescisória",
  EXECUCAO_FISCAL: "Ação de Execução Fiscal",
  EXECUCAO_TITULO_EXTRAJUDICIAL: "Execução de Título Extrajudicial",
  CUMPRIMENTO_SENTENCA: "Cumprimento de Sentença",
  ACAO_ORDINARIA: "Ação Ordinária",
  ACAO_DECLARATORIA: "Ação Declaratória",
  ACAO_ANULATORIA: "Ação Anulatória",
  EMBARGOS_EXECUCAO: "Embargos à Execução",
  EMBARGOS_TERCEIRO: "Embargos de Terceiro",
  RECLAMACAO: "Reclamação",
  CONFLITO_COMPETENCIA: "Conflito de Competência",
  MEDIDA_CAUTELAR: "Medida Cautelar",
  TUTELA_CAUTELAR_ANTECEDENTE: "Tutela Cautelar Antecedente",
  PROCEDIMENTO_COMUM: "Procedimento Comum",
  JUIZADO_ESPECIAL: "Procedimento do Juizado Especial",
  OUTRO: "Outro",
};

export function tipoProcessoLabelPt(
  tipo: TipoProcesso,
  tipoLivre?: string | null,
): string {
  if (tipo === "OUTRO" && tipoLivre && tipoLivre.trim()) {
    return acentuar(tipoLivre.trim());
  }
  return TIPO_PROCESSO_LABELS_PT[tipo];
}

export const RISCO_LABELS_PT: Record<Risco, string> = {
  ALTO: "Alto",
  MEDIO: "Médio",
  BAIXO: "Baixo",
};

export const GRAU_LABELS_PT: Record<Grau, string> = {
  PRIMEIRO: "1º Grau",
  SEGUNDO: "2º Grau",
  SUPERIOR: "Superiores",
};

export const TCE_CAMARA_LABELS_PT = {
  PRIMEIRA: "Primeira Câmara",
  SEGUNDA: "Segunda Câmara",
  PLENO: "Pleno",
} as const;

// Fases judiciais
const FASE_LABELS_PT: Record<string, string> = {
  contestacao_apresentada: "Contestação apresentada",
  aguardando_contestacao: "Aguardando contestação",
  recurso_interposto: "Recurso interposto",
  contrarrazoes_apres: "Contrarrazões apresentadas",
  prazo_provas: "Prazo de provas",
  admissibilidade: "Juízo de admissibilidade",
  admissibilidade_sup: "Admissibilidade (superior)",
  audiencia_agendada: "Audiência agendada",
  sentenca: "Sentença",
  julgamento_ed: "Julgamento de ED (2º grau)",
  julgamento_ed_2grau: "Julgamento de ED (2º grau)",
  ag_alegacoes_finais: "Aguardando alegações finais",
  julgamento_superior: "Julgamento superior",
  pauta_julgamento: "Pauta de julgamento",
  julgamento: "Julgamento (2º grau)",
  julgamento_2grau: "Julgamento (2º grau)",
  alegacoes_finais_apres: "Alegações finais apresentadas",
  concluso_julgamento: "Concluso para julgamento",
  transitado: "Transitado em julgado",
};

export function faseLabelPt(fase: string): string {
  return FASE_LABELS_PT[fase] ?? acentuar(fase);
}

// Fases TCE
const FASE_TCE_LABELS_PT: Record<string, string> = {
  defesa_previa: "Aguardando Defesa Prévia",
  defesa_apresentada: "Defesa Apresentada",
  acordao_1: "Acórdão publicado",
  embargos_1: "Embargos de Declaração interpostos",
  acordao_embargos_1: "Acórdão dos Embargos",
  recurso_ordinario: "Recurso Ordinário interposto",
  acordao_ro: "Acórdão do Recurso Ordinário",
  embargos_ro: "Embargos de Declaração após RO",
  acordao_embargos_ro: "Acórdão dos Embargos pós RO",
  transitado: "Transitado em Julgado",
  manifestacao_previa: "Aguardando Manifestação Prévia",
  manifestacao_apresentada: "Manifestação Apresentada",
  decisao_monocratica: "Decisão Monocrática proferida",
  referendo_pleno: "Em Referendo do Pleno",
  decisao_referendo: "Decisão do Referendo",
  agravo_regimental: "Agravo Regimental interposto",
  acordao_agravo: "Acórdão do Agravo",
  embargos_cautelar: "Embargos de Declaração",
  acordao_embargos_cautelar: "Acórdão dos Embargos",
  transitado_cautelar: "Transitado em Julgado",
};

export function faseTceLabelPt(fase: string): string {
  return FASE_TCE_LABELS_PT[fase] ?? acentuar(fase);
}
